<a href="https://colab.research.google.com/github/julioreis-dev/tutorial_pandas/blob/main/regressao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1,1))
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [3]:
y = np.array([5, 20, 14, 32, 22, 38]).reshape((-1,1))
y

array([[ 5],
       [20],
       [14],
       [32],
       [22],
       [38]])

In [4]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
# 4. Avalia o modelo
print('coeficiente de determinação:', model.score(x, y))

# Intercept
print('intercept:', model.intercept_)

# Slope
print('slope:', model.coef_)



coeficiente de determinação: 0.7158756137479542
intercept: [5.63333333]
slope: [[0.54]]


# **Criação de um novo conjunto de dados**

In [6]:
novo_x = np.arange(5).reshape((-1, 1))
novo_x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [7]:
previsão_y = model.predict(novo_x)
previsão_y

array([[5.63333333],
       [6.17333333],
       [6.71333333],
       [7.25333333],
       [7.79333333]])

In [8]:
horas_estudo = np.array([1, 5, 7, 8, 10, 11, 14, 15, 15, 19]).reshape((-1, 1))
horas_estudo

array([[ 1],
       [ 5],
       [ 7],
       [ 8],
       [10],
       [11],
       [14],
       [15],
       [15],
       [19]])

In [9]:
nota = np.array([53, 74, 59, 43, 56, 84, 96, 69, 84, 83]).reshape((-1, 1))
nota

array([[53],
       [74],
       [59],
       [43],
       [56],
       [84],
       [96],
       [69],
       [84],
       [83]])

In [10]:
modelo = LinearRegression()
modelo.fit(horas_estudo, nota)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
# 4. Avalia o modelo
print('coeficiente de determinação:', modelo.score(x, y))

# Intercept
print('intercept:', modelo.intercept_[0])

# Slope
print('slope:', modelo.coef_[0][0])

coeficiente de determinação: -67.33840049588197
intercept: 49.477126654064264
slope: 1.9640831758034025
