<a href="https://colab.research.google.com/github/julioreis-dev/tutorial_pandas/blob/main/regressao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1,1))
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [3]:
y = np.array([5, 20, 14, 32, 22, 38]).reshape((-1,1))
y

array([[ 5],
       [20],
       [14],
       [32],
       [22],
       [38]])

In [4]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
# 4. Avalia o modelo
print('coeficiente de determinação:', model.score(x, y))

# Intercept
print('intercept:', model.intercept_)

# Slope
print('slope:', model.coef_)



coeficiente de determinação: 0.7158756137479542
intercept: [5.63333333]
slope: [[0.54]]


# **Criação de um novo conjunto de dados**

In [6]:
novo_x = np.arange(5).reshape((-1, 1))
novo_x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [7]:
previsão_y = model.predict(novo_x)
previsão_y

array([[5.63333333],
       [6.17333333],
       [6.71333333],
       [7.25333333],
       [7.79333333]])

In [8]:
horas_estudo = np.array([1, 5, 7, 8, 10, 11, 14, 15, 15, 19]).reshape((-1, 1))
horas_estudo

array([[ 1],
       [ 5],
       [ 7],
       [ 8],
       [10],
       [11],
       [14],
       [15],
       [15],
       [19]])

In [9]:
nota = np.array([53, 74, 59, 43, 56, 84, 96, 69, 84, 83]).reshape((-1, 1))
nota

array([[53],
       [74],
       [59],
       [43],
       [56],
       [84],
       [96],
       [69],
       [84],
       [83]])

In [10]:
modelo = LinearRegression()
modelo.fit(horas_estudo, nota)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
# 4. Avalia o modelo
print('coeficiente de determinação:', modelo.score(x, y))

# Intercept
print('intercept:', modelo.intercept_)

# Slope
print('slope:', modelo.coef_)

coeficiente de determinação: -67.33840049588197
intercept: [49.47712665]
slope: [[1.96408318]]


In [12]:
projeto1_url = '/content/drive/MyDrive/staging/boston.csv'

In [13]:
projeto1 = pd.read_csv(projeto1_url)

In [14]:
projeto1.shape[0]

506

In [15]:
projeto1.head()

Unnamed: 0     CRIM    ZN  INDUS  CHAS  ...    TAX  PTRATIO       B  LSTAT  PRICE
0           0  0.00632  18.0   2.31   0.0  ...  296.0     15.3  396.90   4.98   24.0
1           1  0.02731   0.0   7.07   0.0  ...  242.0     17.8  396.90   9.14   21.6
2           2  0.02729   0.0   7.07   0.0  ...  242.0     17.8  392.83   4.03   34.7
3           3  0.03237   0.0   2.18   0.0  ...  222.0     18.7  394.63   2.94   33.4
4           4  0.06905   0.0   2.18   0.0  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 15 columns]

In [16]:
df_part = pd.read_csv(projeto1_url, nrows=100)

In [17]:
df_part.shape

(100, 15)

In [18]:
df_part.head()

Unnamed: 0     CRIM    ZN  INDUS  CHAS  ...    TAX  PTRATIO       B  LSTAT  PRICE
0           0  0.00632  18.0   2.31   0.0  ...  296.0     15.3  396.90   4.98   24.0
1           1  0.02731   0.0   7.07   0.0  ...  242.0     17.8  396.90   9.14   21.6
2           2  0.02729   0.0   7.07   0.0  ...  242.0     17.8  392.83   4.03   34.7
3           3  0.03237   0.0   2.18   0.0  ...  222.0     18.7  394.63   2.94   33.4
4           4  0.06905   0.0   2.18   0.0  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 15 columns]

In [19]:
df_part2 = projeto1.head(100)

In [20]:
df_part2.shape

(100, 15)

In [21]:
projeto1.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  506 non-null    int64  
 1   CRIM        506 non-null    float64
 2   ZN          506 non-null    float64
 3   INDUS       506 non-null    float64
 4   CHAS        506 non-null    float64
 5   NOX         506 non-null    float64
 6   RM          506 non-null    float64
 7   AGE         506 non-null    float64
 8   DIS         506 non-null    float64
 9   RAD         506 non-null    float64
 10  TAX         506 non-null    float64
 11  PTRATIO     506 non-null    float64
 12  B           506 non-null    float64
 13  LSTAT       506 non-null    float64
 14  PRICE       506 non-null    float64
dtypes: float64(14), int64(1)
memory usage: 59.4 KB


In [22]:
projeto1.memory_usage(deep=True)

Index          128
Unnamed: 0    4048
CRIM          4048
ZN            4048
INDUS         4048
CHAS          4048
NOX           4048
RM            4048
AGE           4048
DIS           4048
RAD           4048
TAX           4048
PTRATIO       4048
B             4048
LSTAT         4048
PRICE         4048
dtype: int64

In [23]:
df_part.info(memory_usage=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  100 non-null    int64  
 1   CRIM        100 non-null    float64
 2   ZN          100 non-null    float64
 3   INDUS       100 non-null    float64
 4   CHAS        100 non-null    float64
 5   NOX         100 non-null    float64
 6   RM          100 non-null    float64
 7   AGE         100 non-null    float64
 8   DIS         100 non-null    float64
 9   RAD         100 non-null    float64
 10  TAX         100 non-null    float64
 11  PTRATIO     100 non-null    float64
 12  B           100 non-null    float64
 13  LSTAT       100 non-null    float64
 14  PRICE       100 non-null    float64
dtypes: float64(14), int64(1)
memory usage: 11.8 KB


In [24]:
df_part.memory_usage(True)

Index         128
Unnamed: 0    800
CRIM          800
ZN            800
INDUS         800
CHAS          800
NOX           800
RM            800
AGE           800
DIS           800
RAD           800
TAX           800
PTRATIO       800
B             800
LSTAT         800
PRICE         800
dtype: int64

In [25]:
df_part2.info(memory_usage=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  100 non-null    int64  
 1   CRIM        100 non-null    float64
 2   ZN          100 non-null    float64
 3   INDUS       100 non-null    float64
 4   CHAS        100 non-null    float64
 5   NOX         100 non-null    float64
 6   RM          100 non-null    float64
 7   AGE         100 non-null    float64
 8   DIS         100 non-null    float64
 9   RAD         100 non-null    float64
 10  TAX         100 non-null    float64
 11  PTRATIO     100 non-null    float64
 12  B           100 non-null    float64
 13  LSTAT       100 non-null    float64
 14  PRICE       100 non-null    float64
dtypes: float64(14), int64(1)
memory usage: 11.8 KB


In [26]:
df_part2.memory_usage(deep=True)

Index         128
Unnamed: 0    800
CRIM          800
ZN            800
INDUS         800
CHAS          800
NOX           800
RM            800
AGE           800
DIS           800
RAD           800
TAX           800
PTRATIO       800
B             800
LSTAT         800
PRICE         800
dtype: int64

In [27]:
x = np.array([[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]])
y = np.array([4, 5, 20, 14, 32, 22, 38, 43])

In [28]:
model = LinearRegression().fit(x, y)

print('coefficient of determination:', model.score(x, y))
print('intercept:', model.intercept_)
print('slope:', model.coef_)

novo_x = np.arange(10).reshape((-1, 2))

previsao_y = model.predict(novo_x)
print(f'Previsão: {previsao_y}')

coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
slope: [0.44706965 0.25502548]
Previsão: [ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]


In [29]:
novo_x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
from glob import glob

In [31]:
files = sorted(glob('/content/drive/MyDrive/staging/*.csv'))
files

['/content/drive/MyDrive/staging/annual_deaths_by_clinic.csv',
 '/content/drive/MyDrive/staging/boston.csv',
 '/content/drive/MyDrive/staging/ipeadata.csv',
 '/content/drive/MyDrive/staging/ipeadata_admissao.csv',
 '/content/drive/MyDrive/staging/ipeadata_demissao.csv',
 '/content/drive/MyDrive/staging/monthly_deaths.csv',
 '/content/drive/MyDrive/staging/titanic.csv']