<a href="https://colab.research.google.com/github/julioreis-dev/tutorial_pandas/blob/main/regressao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1,1))
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [9]:
y = np.array([5, 20, 14, 32, 22, 38])
y

array([ 5, 20, 14, 32, 22, 38])

In [10]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# 4. Avalia o modelo
print('coeficiente de determinação:', model.score(x, y))

# Intercept
print('intercept:', model.intercept_)

# Slope
print('slope:', model.coef_)



coeficiente de determinação: 0.7158756137479542
intercept: 5.633333333333329
slope: [0.54]


# **Criação de um novo modelo**

In [14]:
novo_x = np.arange(5).reshape((-1, 1))
novo_x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [15]:
previsão_y = model.predict(novo_x)
previsão_y

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])