<a href="https://colab.research.google.com/github/julioreis-dev/tutorial_pandas/blob/main/regressao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [16]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1,6))
x

array([[ 5, 15, 25, 35, 45, 55]])

In [10]:
y = np.array([5, 20, 14, 32, 22, 38])
y

array([ 5, 20, 14, 32, 22, 38])

In [ ]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
# 4. Avalia o modelo
print('coeficiente de determinação:', model.score(x, y))

# Intercept
print('intercept:', model.intercept_)

# Slope
print('slope:', model.coef_)



coeficiente de determinação: 0.7158756137479542
intercept: 5.633333333333329
slope: [0.54]


# **Criação de um novo conjunto de dados**

In [ ]:
novo_x = np.arange(5).reshape((-1, 1))
novo_x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
previsão_y = model.predict(novo_x)
previsão_y

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

In [ ]:
horas_estudo = np.array([1, 5, 7, 8, 10, 11, 14, 15, 15, 19]).reshape((-1, 1))
horas_estudo

array([[ 1],
       [ 5],
       [ 7],
       [ 8],
       [10],
       [11],
       [14],
       [15],
       [15],
       [19]])

In [ ]:
nota = np.array([53, 74, 59, 43, 56, 84, 96, 69, 84, 83]).reshape((-1, 1))
nota

array([[53],
       [74],
       [59],
       [43],
       [56],
       [84],
       [96],
       [69],
       [84],
       [83]])

In [22]:
modelo = LinearRegression()
modelo.fit(horas_estudo, nota)

NameError: ignored

In [ ]:
# 4. Avalia o modelo
print('coeficiente de determinação:', modelo.score(x, y))

# Intercept
print('intercept:', modelo.intercept_)

# Slope
print('slope:', modelo.coef_)

coeficiente de determinação: -67.33840049588197
intercept: [49.47712665]
slope: [[1.96408318]]


In [19]:
projeto1_url = '/content/drive/MyDrive/projetos/boston.csv'

In [20]:
projeto1 = pd.read_csv(projeto1_url)

In [21]:
projeto1.head()

Unnamed: 0     CRIM    ZN  INDUS  CHAS  ...    TAX  PTRATIO       B  LSTAT  PRICE
0           0  0.00632  18.0   2.31   0.0  ...  296.0     15.3  396.90   4.98   24.0
1           1  0.02731   0.0   7.07   0.0  ...  242.0     17.8  396.90   9.14   21.6
2           2  0.02729   0.0   7.07   0.0  ...  242.0     17.8  392.83   4.03   34.7
3           3  0.03237   0.0   2.18   0.0  ...  222.0     18.7  394.63   2.94   33.4
4           4  0.06905   0.0   2.18   0.0  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 15 columns]